[package]
name = "lang-macros"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
lang-inner = { path = "../lang-inner", features = ["macro"] }
